apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
stringData:
    user: ENC[AES256_GCM,data:1do6ITtHsHx0szA3G3hfUvqKZ7CX,iv:xhVQ6h84mZJO0yr9vo5RN5taPuNMWzK5LHhr/UYwnrE=,tag:516xbr1bm3cS69aCEMyB+w==,type:str]
    password: ENC[AES256_GCM,data:fIB2IRmojtZ0QdaGuKeVacovzVS4HW5S449DvOg0yv/l7QqWdLILsXc7Sl6UmQi8fo1DYh3IWmvdaCNs9PVxPRiOMze2NufExUxvxdazsstY1CvrZhNh94RJ4DJ28NeBOPsGYw==,iv:DZAbT5PXq4ArHYP68I8qsYd/uTkoRBMF8r/0f4o3gow=,tag:FIVgDMy4TjDgk7eP03hxdA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Bj2THms3ZMaf9a84x0LTjYU209SgEM/RMsI+hottJ3Uan0Ngjkoog+OL1lZaxQ6+htGT87wXFRlzQbHePWyOn0TOyu4l6KOKdr459MyJObUstNpia1WfZbi/tWDyONZPRNqBm3STQWhOTCWL/d517Vubmvz9sfa++u2PGYGiHpc=,iv:A13MkW6HUMPpS7Cy5Dg/OY+3L6KLNQNms8pqLCcG8q8=,tag:ZB6OlZ4wgKxpZI7SNK4GSw==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:NP35eUFJ6VFSNd7bh0K0a/1Spk7ddK+LgD1eCsSm9I08D4rHgHZWrrNnKsVD3wlmoA==,iv:tiM4C96Zi46ripPlonxSbyikp4aw9/O8DWl9KxR5Bx8=,tag:yQUDKhQjC7+MBT499Y5rTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-22T10:15:03Z"
    mac: ENC[AES256_GCM,data:Zog/pobebRmIRFdY9QoIDeKiem3abIxDLEPa4EG5NgC7tuFkNzX3nAigmi+15PknuKhWGLOi/DJotygcF6OCpghNMxoVFuaTiJblbdhWJcMBVr2/rzigHKN+2oyfgGmAYExN3/Zvkb2pZHp1KXNOpwukCX0JvQhcmVuQzGIqTKc=,iv:TRvKSJ5zUokv4b4Xei0SnHTcgTtyJcLug6R2lYtK0MI=,tag:m2rgu4nJjQbad/xSCwInkQ==,type:str]
    pgp:
        - created_at: "2024-03-24T08:14:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA70fE7dz6LU0AQ/9Gh3hJ5ndcaZ+usQsxbB3bd11KueDzzP1+sDEo+bktxUx
            yiI57gPohq3cYPNapZIGqm4fnSIwNaeHr8jYgi/PfZ24Q+etjhgrZUbkkq1gmCT4
            0I+cpqjTnFkbdtKP2LGJCqlf+zL85gfaXvLo4Wn3dejzqiulRPhLE+Ko5dlHFH69
            WaUcxpLuy+vHyezBU0rdd/o45x73+uPidn/lG+ll1daOUm4oa4gOsb5UjIt0QwwJ
            3Lr6b48ed0jlFgcEyDngIMoMrs1xtDiyI0Dhz/+3oLzlI0GF0rXpSf6cUKGF3Hgc
            4D+zw0nUp6+Up233i1OtKw9vIG9ryaceeNom/u19w/YJe8/6mWFPONIbB9mZ6Sa0
            IhElOnQJq5yZILUvgm3KcLnyi07a9TVyQLTwB7QcEbT1aIx/58lJqlcJHacGzZYq
            b+P0x1mK08GkrKg7EMb7me9nDddhZ64XpYYbBgYNyfs1qOX2s3wtJoMZj6tlPauh
            Om640PjoeR5Ca+N32PXtTXEE7TpYduRwVxgQxO/zP2BFwHUNhRqhdgRNSxhKgoq8
            vfh5aITsP8KTUlRggI53DmlUCQ+5BrPopyaFYOVXXViaiouHiObMQIUjVJBtdJv3
            u6dgeFIbRKEEbZwUKEoJ7RaBFpqaMeqE+yzGkNzC4kvX4p8Zyjxqf4fINH4YtdnS
            XgE5kGn23DLxijydjnU9UNlDP7BKzCf7A5HRGxeyfp6DbdaBLHmAVxevTho/x/2f
            WWYrbyPAxqUXttXSukhge8kG44/5RjaEd2buQvwoq3wgcSRvdJuAV+hBpb/FYN8=
            =sbxG
            -----END PGP MESSAGE-----
          fp: 1DF23F1E7AFCAB40F26B210123CFBB30193553AA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
